### ISSUE TITLE
why is there a dependency on postgres 9?  

### ISSUE THREAD

**Issue by chrisdrew1** [cybertec-postgresql/patroni-packaging#5]
Is there a way to leave out the hard dependency of postgres version 9.x libs from this?  As most people that deploy patroni, we use puppet or other method to deploy the postgresqlXX-server libs separately.  Is there a need for version 9?

**Comment by markwort** [comment]
The dependency was always only for the `postgresql-server` package. This was provided by the distribution-provided packages (e.g. some ancient version 9) but also by all other versions of postgresql installed from postgresql.org repositories, which should be the preferred route anyway.

The correct procedure is to install postgresql13-server (e.g.) first and patroni afterwards.
Anyway, this package has been deprecated in favor of the one provided by postgresql.org, so I'm closing this issue.
