### ISSUE TITLE
Question: How to install python36-psycopg2 dependency

### ISSUE THREAD

**Issue by gowtham500** [cybertec-postgresql/patroni-packaging#7]
Hello team,
I tried to install this rpm and found there is a dependency of python36-psycopg2.
Can you please let me know as to how I install this dependency in CentOS 7.

I am unable to find this package in https://yum.postgresql.org/12/redhat/rhel-7.7-x86_64/ as well

**Comment by mart-vi** [comment]
Hello. 
I changed dependency before build in patroni.spec for CentOS Linux release 7.7.1908 (Core)

Requires:      /usr/bin/python3.6, python36-psycopg2 >= 2.5.4, libffi, postgresql-server, libyaml
->
Requires:      /usr/bin/python3.6, python3-psycopg2 >= 2.5.4, libffi, postgresql-server, libyaml


yum install python3-psycopg2
Then installation doesnt complain about missing dependency
